repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.21.0
    hooks:
      - id: pyupgrade
        args: ['--py36-plus']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: check-case-conflict
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
