service: instrument-inventory

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
  stage: ${opt:stage, self:provider.stage}
  environment: ${file(env.yml):${self:custom.stage}, file(env.yml):default}

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1

functions:
  retrieve:
    handler: retrieve.main
    events:
      - http:
          path: retrieve
          method: post
          cors: true
          authorizer: aws_iam

resources:
  - ${file(resources/api-gateway-errors.yml)}
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}