Resources:
  TodosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.todosTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: todoId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: todoId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      Tags:
        -
          Key: 'CostCenter'
          Value: 'Instrument Inventory'
